# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_key',
        ),
        migrations.AddField(
            model_name='farmerasks',
            name='contact_number',
            field=models.CharField(default=5555555555, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verification',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spoken_languages',
            field=models.ManyToManyField(to='agrotrade.Language'),
        ),
    ]
