# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrade', '0002_auto_20190711_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteask',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
