# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-30 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrade', '0007_usersubmission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrotrade.UserProfile'),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(choices=[('Rev', 'Reviewed'), ('Uns', 'Unseen')], default='Uns', max_length=3),
        ),
    ]
