# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-04 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrade', '0008_auto_20200130_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerasks',
            name='medium',
            field=models.CharField(choices=[('Web', 'Web'), ('CC', 'Call Center'), ('SMS', 'SMS')], editable=False, max_length=5),
        ),
    ]
