# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-02-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrade', '0011_auto_20200218_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='spoken_languages',
            field=models.ManyToManyField(blank=True, to='agrotrade.Language'),
        ),
    ]
