# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrotrade', '0012_auto_20200219_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce', models.ManyToManyField(to='agrotrade.ProduceDefinition')),
            ],
        ),
    ]
